### ISSUE TITLE
启动机器人Time out

### ISSUE THREAD

**Issue by jackorjorn** [frankrap/goalgo#1]
请问该如何解决呢？谢谢！

**Comment by frankrap** [comment]
机器人是旧版本，暂时不可用。你可以参考一下新平台，这个增加了回测。
地址: https://github.com/coinrust/gotrader

**Comment by jackorjorn** [comment]
> 机器人是旧版本，暂时不可用。你可以参考一下新平台，这个增加了回测。
> 地址: https://github.com/coinrust/gotrader

好的，谢谢！
挺喜欢这个项目，可惜对GO不了解，安装一个GO, go build 后没生成执行文件。请问有小白步骤吗？^_^

**Comment by frankrap** [comment]
对于项目: https://github.com/coinrust/gotrader
你需要进入示例项目目录: examples/backtest，再执行 go build 即可生成可执行文件
对于go的库项目，是不会生成可执行文件的.

**Comment by jackorjorn** [comment]
> 对于项目: https://github.com/coinrust/gotrader
> 你需要进入示例项目目录: examples/backtest，再执行 go build 即可生成可执行文件
> 对于go的库项目，是不会生成可执行文件的.

测试成功，谢谢！
